# Generated by Django 5.1.6 on 2025-04-16 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='timezone',
            field=models.CharField(default=django.utils.timezone.get_current_timezone_name, max_length=50),
        ),
    ]
